#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kernel-install
Version  : 3
Release  : 1
URL      : https://github.com/clearlinux/kernel-install/archive/v3.tar.gz
Source0  : https://github.com/clearlinux/kernel-install/archive/v3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: kernel-install-bin

%description
No detailed description available

%package bin
Summary: bin components for the kernel-install package.
Group: Binaries

%description bin
bin components for the kernel-install package.


%prep
%setup -q -n kernel-install-3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1524593997
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1524593997
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/installkernel
